default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    sh "cd ../.. && yarn lint"
    sh "cd ../.. && yarn test"
    gradle(task: "test")
  end

  desc "Bundle assets"
  lane :bundle do
    sh "cd ../.. && react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res"
  end

  desc "Generate icons"
  lane :icons do
    android_appicon(appicon_image_file: '../src/assets/launcher.png',
      appicon_icon_types: [:launcher],
      appicon_path: 'app/src/main/res/mipmap',
      appicon_filename: 'ic_launcher')
  end
end
